--- Makefile	2019-07-14 01:50:05.000000000 +0800
+++ Makefile-m	2021-08-02 19:57:54.851281973 +0800
@@ -13,11 +13,12 @@
 # ------------------------------------------------------------------
 
 SHELL=/bin/sh
+CROSS:=
 
 # To assist in cross-compiling
-CC=gcc
-AR=ar
-RANLIB=ranlib
+CC=$(CROSS)gcc
+AR=$(CROSS)ar
+RANLIB=$(CROSS)ranlib
 LDFLAGS=
 
 BIGFILES=-D_FILE_OFFSET_BITS=64
@@ -54,6 +55,7 @@
 
 check: test
 test: bzip2
+ifeq ($(CROSS),)
 	@cat words1
 	./bzip2 -1  < sample1.ref > sample1.rb2
 	./bzip2 -2  < sample2.ref > sample2.rb2
@@ -68,6 +70,7 @@
 	cmp sample2.tst sample2.ref
 	cmp sample3.tst sample3.ref
 	@cat words3
+endif
 
 install: bzip2 bzip2recover
 	if ( test ! -d $(PREFIX)/bin ) ; then mkdir -p $(PREFIX)/bin ; fi
